import {
  Search,
  Heart,
  ShoppingCart,
  User,
  Menu,
  X,
  Star,
  Eye,
  Minus,
  Plus,
  Trash2,
  Sun,
  Moon,
  Phone,
  Monitor,
  Watch,
  Camera,
  Headphones,
  Gamepad2,
  Facebook,
  Twitter,
  Instagram,
  Linkedin,
  Send,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  RotateCcw,
  Truck,
  Check,
  Shirt,
  Home,
  Armchair,
  Footprints,
  Package
} from "lucide-react"

export const Icons = {
  search: Search,
  heart: Heart,
  cart: ShoppingCart,
  user: User,
  menu: Menu,
  close: X,
  star: Star,
  eye: Eye,
  minus: Minus,
  plus: Plus,
  trash: Trash2,
  sun: Sun,
  moon: Moon,
  phone: Phone,
  computer: Monitor,
  watch: Watch,
  camera: Camera,
  headphones: Headphones,
  gaming: Gamepad2,
  facebook: Facebook,
  twitter: Twitter,
  instagram: Instagram,
  linkedin: Linkedin,
  send: Send,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  refresh: RotateCcw,
  truck: Truck,
  check: Check,
  shirt: Shirt,
  home: Home,
  footprints: Footprints,
  package: Package,
  armchair: Armchair,
}